[tool.poetry]
name = "your-app-name"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"  # or your correct version

[tool.poetry.scripts]
start = "main:main"  # If your main.py has a def main()
